name: flutter_sample_async_value
description: Riverpod の AsyncValue を使ったローディングとダイアログとスナックバーのサンプル
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
