name: flutter_sample_async_value
description: Riverpod の AsyncValue を使ったローディングとダイアログとスナックバーのサンプル
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
